// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<your-key-here>',
    appId: '1:478617013237:web:<your-id-here>',
    messagingSenderId: '478617013237',
    projectId: 'madl-exp-9',
    authDomain: 'madl-exp-9.firebaseapp.com',
    storageBucket: 'madl-exp-9.firebasestorage.app',
    databaseURL: 'https://madl-exp-9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<your-key-here>',
    appId: '1:478617013237:android:<your-id-here>',
    messagingSenderId: '478617013237',
    projectId: 'madl-exp-9',
    storageBucket: 'madl-exp-9.firebasestorage.app',
    databaseURL: 'https://madl-exp-9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<your-key-here>',
    appId: '1:478617013237:ios:YOUR_APP_ID',
    messagingSenderId: '478617013237',
    projectId: 'madl-exp-9',
    storageBucket: 'madl-exp-9.firebasestorage.app',
    iosBundleId: 'com.example.madlMiniProject',
    databaseURL: 'https://madl-exp-9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<your-key-here>',
    appId: '1:478617013237:ios:YOUR_APP_ID',
    messagingSenderId: '478617013237',
    projectId: 'madl-exp-9',
    storageBucket: 'madl-exp-9.firebasestorage.app',
    iosBundleId: 'com.example.madlMiniProject',
    databaseURL: 'https://madl-exp-9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '<your-key-here>',
    appId: '1:478617013237:web:<your-id-here>',
    messagingSenderId: '478617013237',
    projectId: 'madl-exp-9',
    authDomain: 'madl-exp-9.firebaseapp.com',
    storageBucket: 'madl-exp-9.firebasestorage.app',
    databaseURL: 'https://madl-exp-9-default-rtdb.firebaseio.com',
  );
}
