# This file configures the analyzer to use the lint rules recommended by the Flutter team.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - prefer_final_fields
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
